### ISSUE TITLE
a large key of lua table not worked

### ISSUE THREAD

**Issue by chinalee-lzh** [yuin/gopher-lua#77] opened 2016-07-12 10:58 UTC
local t = {
    [123456789] = 'A',
}
if I set lua table key = 123456789,  it is not worked

local t = {
    [12345678] = 'A',
}
if i set lua table key = 12345678, it takes long time, almost 7 sec

how can i fix this problem??

**Comment by yuin** [comment] 2016-07-12 12:12
```lua
local t = {
[123456789] = 'A',
}
```

This works for me.

```lua
local t = {
[12345678] = 'A',
}
```

This worked as designed.

You really need numbers as a table index? You can improve performance by using string index instead of large number index

```lua
local t = {
["12345678"] = 'A',
}
```

**Comment by yuin** [comment] 2016-07-19 04:10
Due to lack of your response I am closing this issue for now.
Please feel free to reopen this issue if you have any questions.

**Closed by yuin** 2016-07-19 04:10 UTC
Labels: question
